---
- name: Installing dependencies
  package:
    name: "{{ item }}"
  loop:
    - yum-utils
    - libaio-devel
    - unixODBC
    - unixODBC-devel
  tags:
    - os_packages
  register: os_package_installed

- name: Copying oracle dependencies to zabbix server
  copy:
    src: "{{ item }}"
    dest: /tmp/
    owner: root
    group: root
    mode: 0644
  loop:
    - oracle-instantclient18.5-basic-18.5.0.0.0-3.x86_64.rpm
    - oracle-instantclient18.5-odbc-18.5.0.0.0-3.x86_64.rpm
  tags:
    - copy_packages
  register: copy_oracle_pkg
  when: os_package_installed is success

- name: Installing Oracle dependencies
  yum:
    name: "{{ item }}"
  loop:
    - /tmp/oracle-instantclient18.5-basic-18.5.0.0.0-3.x86_64.rpm
    - /tmp/oracle-instantclient18.5-odbc-18.5.0.0.0-3.x86_64.rpm
  tags:
    - oracle_packages
  when: copy_oracle_pkg is success

- name: Creating link for oracle libs
  file:
    src: '/usr/lib/oracle/18.5/client64/lib/{{ item.filename }}'
    dest: "{{ item.dest }}"
    state: link
  loop:
    - {filename: 'libsqora.so.18.1', dest: '/usr/lib/oracle/18.5/client64/lib/libsqora.so'}
    - { filename: 'libclntsh.so.18.1', dest: '/lib64/libclntsh.so.18.1'}
    - { filename: 'libclntshcore.so.18.1', dest: '/lib64/libclntshcore.so.18.1' }
  register: created_link_to_oracle_libs

- name: Creating /etc/oracle directory
  file:
    path: /etc/oracle
    owner: root
    group: root
    mode: '0755'
    state: directory
  tags:
    - oracle_dir

- name: Insert/Update Oracle ODBC Driver
  blockinfile:
    path: /etc/odbcinst.ini
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    backup: yes
    block: "{{ lookup('file', 'odbcinst.ini') }}"
  tags:
    - odbcinst

- name: Setting up environment files
  copy:
    src: oracle-env.sh
    dest: "{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - /etc/profile.d/oracle-env.sh
    - /etc/sysconfig/zabbix-server
  register: environment_files



